#!/usr/bin/env bash
set -e

# Create project folder if it doesn't exist
mkdir -p 1-new_project
cd 1-new_project || exit 1

# Ensure README.md exists and is not empty (mandatory)
if [ ! -f README.md ]; then
    echo "# 1-new_project" > README.md
    echo "C# console project generated by script." >> README.md
fi

# Initialize new C# console project, force overwrite if files exist
dotnet new console --force

# Restore dependencies (shows output)
dotnet restore

# Build the project (shows output)
dotnet build
