#!/usr/bin/env bash
set -e

# Create project folder
mkdir -p 1-new_project
cd 1-new_project || exit 1

# Ensure README.md exists
if [ ! -f README.md ]; then
    echo "# 1-new_project" > README.md
    echo "C# console project generated by script." >> README.md
fi

# Initialize new C# console project, force overwrite
dotnet new console --force

# Restore dependencies
dotnet restore 2>&1

# Build the project (merge stdout + stderr so checker sees it)
dotnet build 2>&1
